// Generated by build-data.mjs. Do not edit by hand; change the script and re-run it.
// Levels and XP come from Lost City's server content (LostCityRS/Content, rev 274, MIT);
// XP is in tenths, like the server keeps it. Item names, ids and shop values are from
// LostHQ's item database (GPL-3.0). RuneScape is (c) Jagex Ltd.
//
// A method turns "in" items into "out" items. unit, when set, is what one action
// uses (e.g. one essence). multiple: makes floor(level / multiple) + 1 of each
// output per action (runes per essence as Runecraft levels up). kind:
//   xp     - an action you train with (it gives XP)
//   prep   - a step you do on the way (unfinished potions, grinding): planned through
//   source - turns something you already have into an input (filling vials):
//            used when it's in your bank, never put on a shopping list

export const GAME_REVISION = 274;
export const ICON_SIZE = 32;
export const ICONS_PER_ROW = 16;

export const ITEMS = {
  "guamvial":{"id":91,"name":"Guam potion (unf)","cost":3,"members":1,"icon":0},
  "marrentillvial":{"id":93,"name":"Marrentill potion (unf)","cost":5,"members":1,"icon":1},
  "tarrominvial":{"id":95,"name":"Tarromin potion (unf)","cost":11,"members":1,"icon":2},
  "harralandervial":{"id":97,"name":"Harralander potion (unf)","cost":20,"members":1,"icon":3},
  "ranarrvial":{"id":99,"name":"Ranarr potion (unf)","cost":25,"members":1,"icon":4},
  "iritvial":{"id":101,"name":"Irit potion (unf)","cost":40,"members":1,"icon":5},
  "avantoevial":{"id":103,"name":"Avantoe potion (unf)","cost":48,"members":1,"icon":6},
  "kwuarmvial":{"id":105,"name":"Kwuarm potion (unf)","cost":54,"members":1,"icon":7},
  "cadantinevial":{"id":107,"name":"Cadantine potion (unf)","cost":65,"members":1,"icon":8},
  "dwarfweedvial":{"id":109,"name":"Dwarf weed potion (unf)","cost":70,"members":1,"icon":9},
  "torstolvial":{"id":111,"name":"Torstol potion (unf)","cost":25,"members":1,"icon":10},
  "3dose1strength":{"id":115,"name":"Strength potion(3)","cost":13,"icon":11},
  "3dose1attack":{"id":121,"name":"Attack potion(3)","cost":12,"members":1,"icon":12},
  "3dosestatrestore":{"id":127,"name":"Restore potion(3)","cost":88,"members":1,"icon":13},
  "3dose1defense":{"id":133,"name":"Defence potion(3)","cost":120,"members":1,"icon":14},
  "3doseprayerrestore":{"id":139,"name":"Prayer potion(3)","cost":152,"members":1,"icon":15},
  "3dose2attack":{"id":145,"name":"Super attack(3)","cost":180,"members":1,"icon":16},
  "3dosefisherspotion":{"id":151,"name":"Fishing potion(3)","cost":200,"members":1,"icon":17},
  "3dose2strength":{"id":157,"name":"Super strength(3)","cost":220,"members":1,"icon":18},
  "3dose2defense":{"id":163,"name":"Super defence(3)","cost":264,"members":1,"icon":19},
  "3doserangerspotion":{"id":169,"name":"Ranging potion(3)","cost":288,"members":1,"icon":20},
  "3doseantipoison":{"id":175,"name":"Antipoison(3)","cost":288,"members":1,"icon":21},
  "3dose2antipoison":{"id":181,"name":"Superantipoison(3)","cost":288,"members":1,"icon":22},
  "weapon_poison":{"id":187,"name":"Weapon poison","cost":144,"members":1,"icon":23},
  "3dosepotionofzamorak":{"id":189,"name":"Zamorak potion(3)","cost":25,"members":1,"icon":24},
  "unidentified_guam":{"id":199,"name":"Unid herb","cost":1,"members":1,"icon":25},
  "eye_of_newt":{"id":221,"name":"Eye of newt","cost":3,"icon":26},
  "red_spiders_eggs":{"id":223,"name":"Red spiders' eggs","cost":7,"icon":27},
  "limpwurt_root":{"id":225,"name":"Limpwurt root","cost":7,"icon":28},
  "vial_water":{"id":227,"name":"Vial of water","cost":2,"icon":29},
  "vial_empty":{"id":229,"name":"Vial","cost":2,"icon":30},
  "snape_grass":{"id":231,"name":"Snape grass","cost":10,"members":1,"icon":31},
  "pestle_and_mortar":{"id":233,"name":"Pestle and mortar","cost":4,"members":1,"icon":32},
  "unicorn_horn_dust":{"id":235,"name":"Unicorn horn dust","cost":20,"members":1,"icon":33},
  "unicorn_horn":{"id":237,"name":"Unicorn horn","cost":20,"members":1,"icon":34},
  "white_berries":{"id":239,"name":"White berries","cost":10,"members":1,"icon":35},
  "dragon_scale_dust":{"id":241,"name":"Dragon scale dust","cost":52,"members":1,"icon":36},
  "blue_dragon_scale":{"id":243,"name":"Blue dragon scale","cost":50,"members":1,"icon":37},
  "wine_of_zamorak":{"id":245,"name":"Wine of zamorak","cost":1,"icon":38},
  "jangerberries":{"id":247,"name":"Jangerberries","cost":1,"members":1,"icon":39},
  "guam_leaf":{"id":249,"name":"Guam leaf","cost":3,"members":1,"icon":40},
  "marentill":{"id":251,"name":"Marrentill","cost":5,"members":1,"icon":41},
  "tarromin":{"id":253,"name":"Tarromin","cost":11,"members":1,"icon":42},
  "harralander":{"id":255,"name":"Harralander","cost":20,"members":1,"icon":43},
  "ranarr_weed":{"id":257,"name":"Ranarr weed","cost":25,"members":1,"icon":44},
  "irit_leaf":{"id":259,"name":"Irit leaf","cost":40,"members":1,"icon":45},
  "avantoe":{"id":261,"name":"Avantoe","cost":48,"members":1,"icon":46},
  "kwuarm":{"id":263,"name":"Kwuarm","cost":54,"members":1,"icon":47},
  "cadantine":{"id":265,"name":"Cadantine","cost":65,"members":1,"icon":48},
  "dwarf_weed":{"id":267,"name":"Dwarf weed","cost":70,"members":1,"icon":49},
  "torstol":{"id":269,"name":"Torstol","cost":75,"members":1,"icon":50},
  "firerune":{"id":554,"name":"Fire rune","cost":4,"icon":51},
  "waterrune":{"id":555,"name":"Water rune","cost":4,"icon":52},
  "airrune":{"id":556,"name":"Air rune","cost":4,"icon":53},
  "earthrune":{"id":557,"name":"Earth rune","cost":4,"icon":54},
  "mindrune":{"id":558,"name":"Mind rune","cost":3,"icon":55},
  "bodyrune":{"id":559,"name":"Body rune","cost":3,"icon":56},
  "naturerune":{"id":561,"name":"Nature rune","cost":20,"icon":57},
  "chaosrune":{"id":562,"name":"Chaos rune","cost":15,"icon":58},
  "lawrune":{"id":563,"name":"Law rune","cost":40,"icon":59},
  "cosmicrune":{"id":564,"name":"Cosmic rune","cost":15,"icon":60},
  "ashes":{"id":592,"name":"Ashes","cost":2,"icon":61},
  "blankrune":{"id":1436,"name":"Rune essence","cost":4,"icon":62},
  "chocolate_bar":{"id":1973,"name":"Chocolate bar","cost":10,"icon":63},
  "chocolate_dust":{"id":1975,"name":"Chocolate dust","cost":2,"members":1,"icon":64},
  "toads_legs":{"id":2152,"name":"Toad's legs","cost":2,"members":1,"icon":65},
  "4dose1attack":{"id":2428,"name":"Attack potion(4)","cost":15,"members":1,"icon":66},
  "4dosestatrestore":{"id":2430,"name":"Restore potion(4)","cost":110,"members":1,"icon":67},
  "4dose1defense":{"id":2432,"name":"Defence potion(4)","cost":150,"members":1,"icon":68},
  "4doseprayerrestore":{"id":2434,"name":"Prayer potion(4)","cost":190,"members":1,"icon":69},
  "4dose2attack":{"id":2436,"name":"Super attack(4)","cost":225,"members":1,"icon":70},
  "4dosefisherspotion":{"id":2438,"name":"Fishing potion(4)","cost":250,"members":1,"icon":71},
  "4dose2strength":{"id":2440,"name":"Super strength(4)","cost":275,"members":1,"icon":72},
  "4dose2defense":{"id":2442,"name":"Super defence(4)","cost":330,"members":1,"icon":73},
  "4doserangerspotion":{"id":2444,"name":"Ranging potion(4)","cost":360,"members":1,"icon":74},
  "4doseantipoison":{"id":2446,"name":"Antipoison(4)","cost":360,"members":1,"icon":75},
  "4dose2antipoison":{"id":2448,"name":"Superantipoison(4)","cost":360,"members":1,"icon":76},
  "4dosepotionofzamorak":{"id":2450,"name":"Zamorak potion(4)","cost":25,"members":1,"icon":77},
  "4dose1antidragon":{"id":2452,"name":"Antifire potion(4)","cost":330,"members":1,"icon":78},
  "3dose1antidragon":{"id":2454,"name":"Antifire potion(3)","cost":264,"members":1,"icon":79},
  "lantadyme":{"id":2481,"name":"Lantadyme","cost":68,"members":1,"icon":80},
  "lantadymevial":{"id":2483,"name":"Lantadyme potion (unf)","cost":68,"members":1,"icon":81},
  "mortmyremushroom":{"id":2970,"name":"Mort myre fungi","cost":1,"members":1,"icon":82},
  "toadflax":{"id":2998,"name":"Toadflax","cost":48,"members":1,"icon":83},
  "snapdragon":{"id":3000,"name":"Snapdragon","cost":59,"members":1,"icon":84},
  "toadflaxvial":{"id":3002,"name":"Toadflax potion (unf)","cost":48,"members":1,"icon":85},
  "snapdragonvial":{"id":3004,"name":"Snapdragon potion (unf)","cost":59,"members":1,"icon":86},
  "4dose1energy":{"id":3008,"name":"Energy potion(4)","cost":146,"members":1,"icon":87},
  "3dose1energy":{"id":3010,"name":"Energy potion(3)","cost":110,"members":1,"icon":88},
  "4dose2energy":{"id":3016,"name":"Super energy(4)","cost":300,"members":1,"icon":89},
  "3dose2energy":{"id":3018,"name":"Super energy(3)","cost":230,"members":1,"icon":90},
  "4dose2restore":{"id":3024,"name":"Super restore(4)","cost":300,"members":1,"icon":91},
  "3dose2restore":{"id":3026,"name":"Super restore(3)","cost":240,"members":1,"icon":92},
  "4dose1agility":{"id":3032,"name":"Agility potion(4)","cost":200,"members":1,"icon":93},
  "3dose1agility":{"id":3034,"name":"Agility potion(3)","cost":150,"members":1,"icon":94},
  "4dose1magic":{"id":3040,"name":"Magic potion(4)","cost":300,"members":1,"icon":95},
  "3dose1magic":{"id":3042,"name":"Magic potion(3)","cost":250,"members":1,"icon":96},
  "cactus_potato":{"id":3138,"name":"Potato cactus","cost":1,"members":1,"icon":97},
  "mort_serum3":{"id":3410,"name":"Serum 207 (3)","cost":13,"members":1,"icon":98}
};

export const METHODS = [
  {"id":"hb_unf_guam_leaf","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Guam potion (unf)","level":3,"xp":0,"in":{"guam_leaf":1,"vial_water":1},"out":{"guamvial":1}},
  {"id":"hb_unf_marentill","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Marrentill potion (unf)","level":5,"xp":0,"in":{"marentill":1,"vial_water":1},"out":{"marrentillvial":1}},
  {"id":"hb_unf_tarromin","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Tarromin potion (unf)","level":12,"xp":0,"in":{"tarromin":1,"vial_water":1},"out":{"tarrominvial":1}},
  {"id":"hb_unf_harralander","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Harralander potion (unf)","level":22,"xp":0,"in":{"harralander":1,"vial_water":1},"out":{"harralandervial":1}},
  {"id":"hb_unf_ranarr_weed","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Ranarr potion (unf)","level":30,"xp":0,"in":{"ranarr_weed":1,"vial_water":1},"out":{"ranarrvial":1}},
  {"id":"hb_unf_toadflax","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Toadflax potion (unf)","level":34,"xp":0,"in":{"toadflax":1,"vial_water":1},"out":{"toadflaxvial":1}},
  {"id":"hb_unf_irit_leaf","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Irit potion (unf)","level":45,"xp":0,"in":{"irit_leaf":1,"vial_water":1},"out":{"iritvial":1}},
  {"id":"hb_unf_avantoe","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Avantoe potion (unf)","level":50,"xp":0,"in":{"avantoe":1,"vial_water":1},"out":{"avantoevial":1}},
  {"id":"hb_unf_kwuarm","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Kwuarm potion (unf)","level":55,"xp":0,"in":{"kwuarm":1,"vial_water":1},"out":{"kwuarmvial":1}},
  {"id":"hb_unf_snapdragon","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Snapdragon potion (unf)","level":63,"xp":0,"in":{"snapdragon":1,"vial_water":1},"out":{"snapdragonvial":1}},
  {"id":"hb_unf_cadantine","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Cadantine potion (unf)","level":66,"xp":0,"in":{"cadantine":1,"vial_water":1},"out":{"cadantinevial":1}},
  {"id":"hb_unf_lantadyme","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Lantadyme potion (unf)","level":69,"xp":0,"in":{"lantadyme":1,"vial_water":1},"out":{"lantadymevial":1}},
  {"id":"hb_unf_dwarf_weed","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Dwarf weed potion (unf)","level":72,"xp":0,"in":{"dwarf_weed":1,"vial_water":1},"out":{"dwarfweedvial":1}},
  {"id":"hb_unf_torstol","skill":"herblore","group":"Unfinished potions","kind":"prep","name":"Torstol potion (unf)","level":78,"xp":0,"in":{"torstol":1,"vial_water":1},"out":{"torstolvial":1}},
  {"id":"hb_3dose1attack","skill":"herblore","group":"Potions","kind":"xp","name":"Attack potion","level":3,"xp":250,"in":{"guamvial":1,"eye_of_newt":1},"out":{"3dose1attack":1}},
  {"id":"hb_3doseantipoison","skill":"herblore","group":"Potions","kind":"xp","name":"Antipoison","level":5,"xp":375,"in":{"marrentillvial":1,"unicorn_horn_dust":1},"out":{"3doseantipoison":1}},
  {"id":"hb_3dose1strength","skill":"herblore","group":"Potions","kind":"xp","name":"Strength potion","level":12,"xp":500,"in":{"tarrominvial":1,"limpwurt_root":1},"out":{"3dose1strength":1}},
  {"id":"hb_mort_serum3","skill":"herblore","group":"Potions","kind":"xp","name":"Serum 207","level":15,"xp":500,"in":{"tarrominvial":1,"ashes":1},"out":{"mort_serum3":1}},
  {"id":"hb_3dosestatrestore","skill":"herblore","group":"Potions","kind":"xp","name":"Restore potion","level":22,"xp":625,"in":{"harralandervial":1,"red_spiders_eggs":1},"out":{"3dosestatrestore":1}},
  {"id":"hb_3dose1energy","skill":"herblore","group":"Potions","kind":"xp","name":"Energy potion","level":26,"xp":675,"in":{"harralandervial":1,"chocolate_dust":1},"out":{"3dose1energy":1}},
  {"id":"hb_3dose1defense","skill":"herblore","group":"Potions","kind":"xp","name":"Defence potion","level":30,"xp":750,"in":{"ranarrvial":1,"white_berries":1},"out":{"3dose1defense":1}},
  {"id":"hb_3dose1agility","skill":"herblore","group":"Potions","kind":"xp","name":"Agility potion","level":34,"xp":800,"in":{"toadflaxvial":1,"toads_legs":1},"out":{"3dose1agility":1}},
  {"id":"hb_3doseprayerrestore","skill":"herblore","group":"Potions","kind":"xp","name":"Prayer potion","level":38,"xp":875,"in":{"ranarrvial":1,"snape_grass":1},"out":{"3doseprayerrestore":1}},
  {"id":"hb_3dose2attack","skill":"herblore","group":"Potions","kind":"xp","name":"Super attack","level":45,"xp":1000,"in":{"iritvial":1,"eye_of_newt":1},"out":{"3dose2attack":1}},
  {"id":"hb_3dose2antipoison","skill":"herblore","group":"Potions","kind":"xp","name":"Superantipoison","level":48,"xp":1063,"in":{"iritvial":1,"unicorn_horn_dust":1},"out":{"3dose2antipoison":1}},
  {"id":"hb_3dosefisherspotion","skill":"herblore","group":"Potions","kind":"xp","name":"Fishing potion","level":50,"xp":1125,"in":{"avantoevial":1,"snape_grass":1},"out":{"3dosefisherspotion":1}},
  {"id":"hb_3dose2energy","skill":"herblore","group":"Potions","kind":"xp","name":"Super energy","level":52,"xp":1175,"in":{"avantoevial":1,"mortmyremushroom":1},"out":{"3dose2energy":1}},
  {"id":"hb_3dose2strength","skill":"herblore","group":"Potions","kind":"xp","name":"Super strength","level":55,"xp":1250,"in":{"kwuarmvial":1,"limpwurt_root":1},"out":{"3dose2strength":1}},
  {"id":"hb_weapon_poison","skill":"herblore","group":"Potions","kind":"xp","name":"Weapon poison","level":60,"xp":1375,"in":{"kwuarmvial":1,"dragon_scale_dust":1},"out":{"weapon_poison":1}},
  {"id":"hb_3dose2restore","skill":"herblore","group":"Potions","kind":"xp","name":"Super restore","level":63,"xp":1425,"in":{"snapdragonvial":1,"red_spiders_eggs":1},"out":{"3dose2restore":1}},
  {"id":"hb_3dose2defense","skill":"herblore","group":"Potions","kind":"xp","name":"Super defence","level":66,"xp":1500,"in":{"cadantinevial":1,"white_berries":1},"out":{"3dose2defense":1}},
  {"id":"hb_3dose1antidragon","skill":"herblore","group":"Potions","kind":"xp","name":"Antifire potion","level":69,"xp":1575,"in":{"lantadymevial":1,"dragon_scale_dust":1},"out":{"3dose1antidragon":1}},
  {"id":"hb_3doserangerspotion","skill":"herblore","group":"Potions","kind":"xp","name":"Ranging potion","level":72,"xp":1625,"in":{"dwarfweedvial":1,"wine_of_zamorak":1},"out":{"3doserangerspotion":1}},
  {"id":"hb_3dose1magic","skill":"herblore","group":"Potions","kind":"xp","name":"Magic potion","level":76,"xp":1725,"in":{"lantadymevial":1,"cactus_potato":1},"out":{"3dose1magic":1}},
  {"id":"hb_3dosepotionofzamorak","skill":"herblore","group":"Potions","kind":"xp","name":"Zamorak potion","level":78,"xp":1750,"in":{"torstolvial":1,"jangerberries":1},"out":{"3dosepotionofzamorak":1}},
  {"id":"hb_fill_vial","skill":"herblore","group":"Supplies","kind":"source","name":"Fill vials with water","level":1,"xp":0,"in":{"vial_empty":1},"out":{"vial_water":1}},
  {"id":"hb_grind_unicorn_horn","skill":"herblore","group":"Grinding","kind":"prep","tools":["pestle_and_mortar"],"name":"Grind unicorn horn","level":1,"xp":0,"in":{"unicorn_horn":1},"out":{"unicorn_horn_dust":1}},
  {"id":"hb_grind_chocolate_bar","skill":"herblore","group":"Grinding","kind":"prep","tools":["pestle_and_mortar"],"name":"Grind chocolate bar","level":1,"xp":0,"in":{"chocolate_bar":1},"out":{"chocolate_dust":1}},
  {"id":"hb_grind_blue_dragon_scale","skill":"herblore","group":"Grinding","kind":"prep","tools":["pestle_and_mortar"],"name":"Grind blue dragon scale","level":1,"xp":0,"in":{"blue_dragon_scale":1},"out":{"dragon_scale_dust":1}},
  {"id":"rc_airrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Air rune","level":1,"xp":50,"in":{"blankrune":1},"out":{"airrune":1},"multiple":11},
  {"id":"rc_mindrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Mind rune","level":2,"xp":55,"in":{"blankrune":1},"out":{"mindrune":1},"multiple":14},
  {"id":"rc_waterrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Water rune","level":5,"xp":60,"in":{"blankrune":1},"out":{"waterrune":1},"multiple":19},
  {"id":"rc_earthrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Earth rune","level":9,"xp":65,"in":{"blankrune":1},"out":{"earthrune":1},"multiple":26},
  {"id":"rc_firerune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Fire rune","level":14,"xp":70,"in":{"blankrune":1},"out":{"firerune":1},"multiple":35},
  {"id":"rc_bodyrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Body rune","level":20,"xp":75,"in":{"blankrune":1},"out":{"bodyrune":1},"multiple":46},
  {"id":"rc_cosmicrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Cosmic rune","level":27,"xp":80,"in":{"blankrune":1},"out":{"cosmicrune":1},"multiple":59},
  {"id":"rc_chaosrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Chaos rune","level":35,"xp":85,"in":{"blankrune":1},"out":{"chaosrune":1},"multiple":74},
  {"id":"rc_naturerune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Nature rune","level":44,"xp":90,"in":{"blankrune":1},"out":{"naturerune":1},"multiple":91},
  {"id":"rc_lawrune","skill":"runecraft","group":"Runes","kind":"xp","unit":"essence","name":"Law rune","level":54,"xp":95,"in":{"blankrune":1},"out":{"lawrune":1}},
];

// Unidentified herbs: one bank entry (the market's unid listing), and the XP
// identifying one gives, in tenths, lowest and highest across the herbs.
export const UNID_HERBS = {"item":"unidentified_guam","xpMin":25,"xpMax":150};

// What the Bank tab lists for each skill, in groups.
export const BANK_GROUPS = {
  "herblore": [
    {
      "name": "Herbs",
      "items": [
        "guam_leaf",
        "marentill",
        "tarromin",
        "harralander",
        "ranarr_weed",
        "toadflax",
        "irit_leaf",
        "avantoe",
        "kwuarm",
        "snapdragon",
        "cadantine",
        "lantadyme",
        "dwarf_weed",
        "torstol",
        "unidentified_guam"
      ]
    },
    {
      "name": "Unfinished potions",
      "items": [
        "guamvial",
        "marrentillvial",
        "tarrominvial",
        "harralandervial",
        "ranarrvial",
        "toadflaxvial",
        "iritvial",
        "avantoevial",
        "kwuarmvial",
        "snapdragonvial",
        "cadantinevial",
        "lantadymevial",
        "dwarfweedvial",
        "torstolvial"
      ]
    },
    {
      "name": "Secondaries",
      "items": [
        "eye_of_newt",
        "unicorn_horn_dust",
        "limpwurt_root",
        "ashes",
        "red_spiders_eggs",
        "chocolate_dust",
        "white_berries",
        "toads_legs",
        "snape_grass",
        "mortmyremushroom",
        "dragon_scale_dust",
        "wine_of_zamorak",
        "cactus_potato",
        "jangerberries"
      ]
    },
    {
      "name": "To grind",
      "items": [
        "unicorn_horn",
        "chocolate_bar",
        "blue_dragon_scale"
      ]
    },
    {
      "name": "Supplies",
      "items": [
        "vial_water",
        "vial_empty"
      ]
    },
    {
      "name": "Potions",
      "items": [
        "3dose1attack",
        "3doseantipoison",
        "3dose1strength",
        "mort_serum3",
        "3dosestatrestore",
        "3dose1energy",
        "3dose1defense",
        "3dose1agility",
        "3doseprayerrestore",
        "3dose2attack",
        "3dose2antipoison",
        "3dosefisherspotion",
        "3dose2energy",
        "3dose2strength",
        "weapon_poison",
        "3dose2restore",
        "3dose2defense",
        "3dose1antidragon",
        "3doserangerspotion",
        "3dose1magic",
        "3dosepotionofzamorak"
      ]
    }
  ],
  "runecraft": [
    {
      "name": "Essence",
      "items": [
        "blankrune"
      ]
    },
    {
      "name": "Runes",
      "items": [
        "airrune",
        "mindrune",
        "waterrune",
        "earthrune",
        "firerune",
        "bodyrune",
        "cosmicrune",
        "chaosrune",
        "naturerune",
        "lawrune"
      ]
    }
  ]
};
